def write_fvsolution(file_manager):
    file_id = file_manager.create_file('system', 'fvSolution')
    file_manager.write_header(file_id, 'dictionary', 'system', 'fvSolution')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'solvers\n{\n')
    file_manager.write(file_id, '    p\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        solver           GAMG;\n')
    file_manager.write(file_id, '        smoother         FDIC;\n')
    file_manager.write(file_id, '        tolerance        1e-08;\n')
    file_manager.write(file_id, '        relTol           0.01;\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '    pFinal\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        $p;\n')
    file_manager.write(file_id, '        relTol           0;\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '    "(U|k|omega|epsilon|nuTilda|zeta)"\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        solver           PBiCGStab;\n')
    file_manager.write(file_id, '        preconditioner   DILU;\n')
    file_manager.write(file_id, '        tolerance        1e-08;\n')
    file_manager.write(file_id, '        relTol           0.01;\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '    "(UFinal|kFinal|omegaFinal|epsilonFinal|nuTildaFinal|zetaFinal)"\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        $U;\n')
    file_manager.write(file_id, '        relTol           0;\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '"(SIMPLE|PISO)"\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    consistent                 yes;\n')
    file_manager.write(file_id, '    nCorrectors                2;\n')
    file_manager.write(file_id, '    nNonOrthogonalCorrectors   0;\n')
    file_manager.write(file_id, '    pRefCell                   0;\n')
    file_manager.write(file_id, '    pRefValue                  0;\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '    residualControl\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        U         1e-6;\n')
    file_manager.write(file_id, '        p         1e-6;\n')
    file_manager.write(file_id, '        k         1e-6;\n')
    file_manager.write(file_id, '        omega     1e-6;\n')
    file_manager.write(file_id, '        epsilon   1e-6;\n')
    file_manager.write(file_id, '        nuTilda   1e-6;\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'relaxationFactors\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    fields\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        p         0.3;\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '    equations\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        U         0.7;\n')
    file_manager.write(file_id, '        k         0.7;\n')
    file_manager.write(file_id, '        omega     0.7;\n')
    file_manager.write(file_id, '        epsilon   0.7;\n')
    file_manager.write(file_id, '        nuTilda   0.7;\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '// ************************************************************************* //\n')
    file_id.close()
