import os
import FileManager as Header


def write_fvschemes(case_name, version):
    file_id = open(os.path.join(case_name, 'system', 'fvSchemes'), "w")
    Header.write_header(file_id, version, 'fvSolution', 'system', 'dictionary')
    file_id.write('\n')
    file_id.write('ddtSchemes\n')
    file_id.write('{\n')
    file_id.write('    default         backward;\n')
    file_id.write('}\n')
    file_id.write('\n')
    file_id.write('gradSchemes\n')
    file_id.write('{\n')
    file_id.write('    default         Gauss linear;\n')
    file_id.write('}\n')
    file_id.write('\n')
    file_id.write('divSchemes\n')
    file_id.write('{\n')
    file_id.write('    default         Gauss upwind grad(U);\n')
    file_id.write('    div(phi,U)      Gauss linearUpwind grad(U);\n')
    file_id.write('    div((nuEff*dev2(T(grad(U))))) Gauss linear;\n')
    file_id.write('}\n')
    file_id.write('\n')
    file_id.write('laplacianSchemes\n')
    file_id.write('{\n')
    file_id.write('    default         Gauss linear orthogonal;\n')
    file_id.write('}\n')
    file_id.write('\n')
    file_id.write('interpolationSchemes\n')
    file_id.write('{\n')
    file_id.write('    default         linear;\n')
    file_id.write('}\n')
    file_id.write('\n')
    file_id.write('snGradSchemes\n')
    file_id.write('{\n')
    file_id.write('    default         orthogonal;\n')
    file_id.write('}\n')
    file_id.write('\n')
    file_id.write('wallDist\n')
    file_id.write('{\n')
    file_id.write('    method          meshWave;\n')
    file_id.write('}\n')
    file_id.write('\n')
    file_id.write('// ************************************************************************* //\n')
    file_id.close()