def write_fvsolution(file_manager, solver_properties):
    file_id = file_manager.create_file('system', 'fvSolution')
    file_manager.write_header(file_id, 'dictionary', 'system', 'fvSolution')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'solvers\n{\n')
    file_manager.write(file_id, '    p\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        solver           GAMG;\n')
    file_manager.write(file_id, '        smoother         FDIC;\n')
    file_manager.write(file_id, '        tolerance        ' + str(solver_properties['absolute_convergence_criterion']) + ';\n')
    file_manager.write(file_id, '        relTol           ' + str(solver_properties['relative_convergence_criterion']) + ';\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '    pFinal\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        $p;\n')
    file_manager.write(file_id, '        relTol           0;\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '    "(U|k|omega|epsilon|nuTilda|zeta)"\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        solver           PBiCGStab;\n')
    file_manager.write(file_id, '        preconditioner   DILU;\n')
    file_manager.write(file_id, '        tolerance        ' + str(solver_properties['absolute_convergence_criterion']) + ';\n')
    file_manager.write(file_id, '        relTol           ' + str(solver_properties['relative_convergence_criterion']) + ';\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '    "(UFinal|kFinal|omegaFinal|epsilonFinal|nuTildaFinal|zetaFinal)"\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        $U;\n')
    file_manager.write(file_id, '        relTol           0;\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '"(SIMPLE|PISO)"\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    consistent                 yes;\n')
    file_manager.write(file_id, '    nCorrectors                2;\n')
    file_manager.write(file_id, '    nNonOrthogonalCorrectors   0;\n')
    file_manager.write(file_id, '    pRefCell                   0;\n')
    file_manager.write(file_id, '    pRefValue                  0;\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '    residualControl\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        U         ' + str(solver_properties['convergence_threshold']) + ';\n')
    file_manager.write(file_id, '        p         ' + str(solver_properties['convergence_threshold']) + ';\n')
    file_manager.write(file_id, '        k         ' + str(solver_properties['convergence_threshold']) + ';\n')
    file_manager.write(file_id, '        omega     ' + str(solver_properties['convergence_threshold']) + ';\n')
    file_manager.write(file_id, '        epsilon   ' + str(solver_properties['convergence_threshold']) + ';\n')
    file_manager.write(file_id, '        nuTilda   ' + str(solver_properties['convergence_threshold']) + ';\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'relaxationFactors\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    fields\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        p         ' + str(solver_properties['under_relaxation_p']) + ';\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '    equations\n')
    file_manager.write(file_id, '    {\n')
    file_manager.write(file_id, '        U         ' + str(solver_properties['under_relaxation_U']) + ';\n')
    file_manager.write(file_id, '        k         ' + str(solver_properties['under_relaxation_turbulence']) + ';\n')
    file_manager.write(file_id, '        omega     ' + str(solver_properties['under_relaxation_turbulence']) + ';\n')
    file_manager.write(file_id, '        epsilon   ' + str(solver_properties['under_relaxation_turbulence']) + ';\n')
    file_manager.write(file_id, '        nuTilda   ' + str(solver_properties['under_relaxation_turbulence']) + ';\n')
    file_manager.write(file_id, '    }\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '// ************************************************************************* //\n')
    file_id.close()
