def write_control_dict(file_manager, solver_properties):
    file_id = file_manager.create_file('system', 'controlDict')
    file_manager.write_header(file_id, 'dictionary', 'system', 'controlDict')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'application       ' + solver_properties['solver'] + ';\n\n')
    file_manager.write(file_id, 'startFrom         startTime;\n\n')
    file_manager.write(file_id, 'startTime         0;\n\n')
    file_manager.write(file_id, 'stopAt            endTime;\n\n')
    file_manager.write(file_id, 'endTime           1000;\n\n')
    file_manager.write(file_id, 'deltaT            0.1;\n\n')
    file_manager.write(file_id, 'maxDeltaT         1;\n\n')
    file_manager.write(file_id, 'adjustTimeStep    yes;\n\n')
    file_manager.write(file_id, 'maxCo             1.0;\n\n')
    file_manager.write(file_id, 'writeControl      timeStep;\n\n')
    file_manager.write(file_id, 'writeInterval     10;\n\n')
    file_manager.write(file_id, 'purgeWrite        0;\n\n')
    file_manager.write(file_id, 'writeFormat       ascii;\n\n')
    file_manager.write(file_id, 'writePrecision    6;\n\n')
    file_manager.write(file_id, 'writeCompression  off;\n\n')
    file_manager.write(file_id, 'timeFormat        general;\n\n')
    file_manager.write(file_id, 'timePrecision     6;\n\n')
    file_manager.write(file_id, 'runTimeModifiable true;\n\n')
    file_manager.write(file_id, '// ************************************************************************* //\n')
    file_id.close()
