def write_fvschemes(file_manager):
    file_id = file_manager.create_file('system', 'fvSchemes')
    file_manager.write_header(file_id, 'dictionary', 'system', 'fvSchemes')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'ddtSchemes\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    default         backward;\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'gradSchemes\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    default         Gauss linear;\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'divSchemes\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    default         Gauss upwind grad(U);\n')
    file_manager.write(file_id, '    div(phi,U)      Gauss linearUpwind grad(U);\n')
    file_manager.write(file_id, '    div((nuEff*dev2(T(grad(U))))) Gauss linear;\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'laplacianSchemes\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    default         Gauss linear orthogonal;\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'interpolationSchemes\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    default         linear;\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'snGradSchemes\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    default         orthogonal;\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, 'wallDist\n')
    file_manager.write(file_id, '{\n')
    file_manager.write(file_id, '    method          meshWave;\n')
    file_manager.write(file_id, '}\n')
    file_manager.write(file_id, '\n')
    file_manager.write(file_id, '// ************************************************************************* //\n')
    file_id.close()
