import os
import FileManager as Header


def write_fvsolution(case_name, version):
    file_id = open(os.path.join(case_name, 'system', 'fvSolution'), "w")
    Header.write_header(file_id, version, 'fvSolution', 'system', 'dictionary')
    file_id.write('\n')
    file_id.write('solvers\n{\n')
    file_id.write('    p\n')
    file_id.write('    {\n')
    file_id.write('        solver           GAMG;\n')
    file_id.write('        smoother         FDIC;\n')
    file_id.write('        tolerance        1e-08;\n')
    file_id.write('        relTol           0.01;\n')
    file_id.write('    }\n')
    file_id.write('\n')
    file_id.write('    pFinal\n')
    file_id.write('    {\n')
    file_id.write('        $p;\n')
    file_id.write('        relTol           0;\n')
    file_id.write('    }\n')
    file_id.write('\n')
    file_id.write('    "(U|k|omega|epsilon|nuTilda)"\n')
    file_id.write('    {\n')
    file_id.write('        solver           PBiCGStab;\n')
    file_id.write('        preconditioner   DILU;\n')
    file_id.write('        tolerance        1e-08;\n')
    file_id.write('        relTol           0.01;\n')
    file_id.write('    }\n')
    file_id.write('\n')
    file_id.write('    "(UFinal|kFinal|omegaFinal|epsilonFinal|nuTildaFinal)"\n')
    file_id.write('    {\n')
    file_id.write('        $U;\n')
    file_id.write('        relTol           0;\n')
    file_id.write('    }\n')
    file_id.write('}\n')
    file_id.write('\n')
    file_id.write('"(SIMPLE|PISO)"\n')
    file_id.write('{\n')
    file_id.write('    consistent                 yes;\n')
    file_id.write('    nCorrectors                2;\n')
    file_id.write('    nNonOrthogonalCorrectors   0;\n')
    file_id.write('    pRefCell                   0;\n')
    file_id.write('    pRefValue                  0;\n')
    file_id.write('\n')
    file_id.write('    residualControl\n')
    file_id.write('    {\n')
    file_id.write('        U         1e-6;\n')
    file_id.write('        p         1e-6;\n')
    file_id.write('        k         1e-6;\n')
    file_id.write('        omega     1e-6;\n')
    file_id.write('        epsilon   1e-6;\n')
    file_id.write('        nuTilda   1e-6;\n')
    file_id.write('    }\n')
    file_id.write('}\n')
    file_id.write('\n')
    file_id.write('relaxationFactors\n')
    file_id.write('{\n')
    file_id.write('    fields\n')
    file_id.write('    {\n')
    file_id.write('        p         0.3\n')
    file_id.write('    }\n')
    file_id.write('\n')
    file_id.write('    equations\n')
    file_id.write('    {\n')
    file_id.write('        U         0.7\n')
    file_id.write('        k         0.7\n')
    file_id.write('        omega     0.7\n')
    file_id.write('        epsilon   0.7\n')
    file_id.write('        nuTilda   0.7\n')
    file_id.write('    }\n')
    file_id.write('}\n')
    file_id.write('\n')
    file_id.write('// ************************************************************************* //\n')
    file_id.close()
